name: ayaka
description: "A Flutter for hitomi"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hitomi:
    path: ../hitomi
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.30
  easy_image_viewer: ^1.5.1
  provider: ^6.1.2
  collection: ^1.19.1
  intl: ^0.20.2
  file_picker: ^10.1.2
  card_loading: ^0.3.2
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.1
  image: ^4.5.2
  file_saver: ^0.2.14
  dio: ^5.8.0+1
  flutter_cache_manager: ^3.4.1
  sqflite_common_ffi: ^2.3.5
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
dependency_overrides:
  test_api: 0.7.4
  intl: ^0.20.2
  async: ^2.13.0