name: ayaka
description: "A Flutter for hitomi"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hitomi:
    path: ../hitomi
  shared_preferences: ^2.3.0
  path_provider: ^2.1.4
  path: ^1.9.0
  sqlite3: ^2.4.5
  sqlite3_flutter_libs: ^0.5.24
  easy_image_viewer: ^1.5.1
  provider: ^6.1.2
  collection: ^1.19.0
  intl: ^0.19.0
  file_picker: ^8.0.6
  card_loading: ^0.3.2
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  image: ^4.2.0
  file_saver: ^0.2.13
  dio: ^5.5.0+1
  flutter_cache_manager: ^3.3.2
  sqflite_common_ffi: ^2.3.3
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
dependency_overrides:
  test_api: 0.6.0
  collection: ^1.19.0